# Generated by Django 4.0.6 on 2022-09-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'داده', 'verbose_name_plural': 'اطلاعات'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='alt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(help_text='به تومان وارد کنید.', verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='اختیاری', max_length=125, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, help_text='آیا نمایش داده شود؟', verbose_name='وضعیت'),
        ),
    ]
