# Generated by Django 4.0.6 on 2022-09-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_thumbnail_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, help_text='اختیاری', max_length=258, verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='آدرس صفحه'),
        ),
    ]
